In [1]:
import os
from glob import glob # extract path of each file
import pandas as pd # data preprocessing
from xml.etree import ElementTree as et # parse information from XML
from functools import reduce

In [2]:
import warnings
warnings.filterwarnings('ignore')

### step-1: get path of each xml file

In [37]:
xmlfiles = glob('./dataset/*.xml')
# replace \\ with /
replace_text = lambda x: x.replace('\\','/')
xmlfiles = list(map(replace_text,xmlfiles))

In [38]:
xmlfiles

['./dataset/001.xml',
 './dataset/002.xml',
 './dataset/003.xml',
 './dataset/004.xml',
 './dataset/005.xml',
 './dataset/006.xml',
 './dataset/007.xml',
 './dataset/008.xml',
 './dataset/009.xml',
 './dataset/010.xml',
 './dataset/011.xml',
 './dataset/012.xml',
 './dataset/013.xml',
 './dataset/014.xml',
 './dataset/015.xml',
 './dataset/016.xml',
 './dataset/017.xml',
 './dataset/018.xml',
 './dataset/019.xml',
 './dataset/020.xml',
 './dataset/021.xml',
 './dataset/022.xml',
 './dataset/023.xml',
 './dataset/024.xml',
 './dataset/025.xml',
 './dataset/026.xml',
 './dataset/027.xml',
 './dataset/028.xml',
 './dataset/029.xml',
 './dataset/030.xml',
 './dataset/031.xml',
 './dataset/032.xml',
 './dataset/033.xml',
 './dataset/034.xml',
 './dataset/035.xml',
 './dataset/036.xml',
 './dataset/037.xml',
 './dataset/038.xml',
 './dataset/039.xml',
 './dataset/040.xml',
 './dataset/041.xml',
 './dataset/042.xml',
 './dataset/043.xml',
 './dataset/044.xml',
 './dataset/045.xml',
 './dataset/046.xml',
 './dataset/047.xml',
 './dataset/048.xml',
 './dataset/049.xml',
 './dataset/050.xml',
 './dataset/051.xml',
 './dataset/052.xml',
 './dataset/053.xml',
 './dataset/054.xml',
 './dataset/055.xml',
 './dataset/056.xml',
 './dataset/057.xml',
 './dataset/058.xml',
 './dataset/059.xml',
 './dataset/060.xml',
 './dataset/061.xml',
 './dataset/062.xml',
 './dataset/063.xml',
 './dataset/064.xml',
 './dataset/065.xml',
 './dataset/066.xml',
 './dataset/067.xml',
 './dataset/068.xml',
 './dataset/069.xml',
 './dataset/070.xml',
 './dataset/071.xml',
 './dataset/072.xml',
 './dataset/073.xml',
 './dataset/074.xml',
 './dataset/075.xml',
 './dataset/076.xml',
 './dataset/077.xml',
 './dataset/078.xml',
 './dataset/079.xml',
 './dataset/080.xml',
 './dataset/081.xml',
 './dataset/082.xml',
 './dataset/083.xml',
 './dataset/084.xml',
 './dataset/085.xml',
 './dataset/086.xml',
 './dataset/087.xml',
 './dataset/088.xml',
 './dataset/089.xml',
 './dataset/090.xml',
 './dataset/091.xml',
 './dataset/092.xml',
 './dataset/093.xml',
 './dataset/094.xml',
 './dataset/095.xml',
 './dataset/096.xml',
 './dataset/097.xml',
 './dataset/098.xml',
 './dataset/099.xml',
 './dataset/100.xml',
 './dataset/101.xml',
 './dataset/102.xml',
 './dataset/103.xml',
 './dataset/104.xml',
 './dataset/105.xml',
 './dataset/106.xml',
 './dataset/107.xml',
 './dataset/108.xml',
 './dataset/109.xml',
 './dataset/110.xml',
 './dataset/111.xml',
 './dataset/112.xml',
 './dataset/113.xml',
 './dataset/114.xml',
 './dataset/115.xml',
 './dataset/116.xml',
 './dataset/117.xml',
 './dataset/118.xml',
 './dataset/119.xml',
 './dataset/120.xml',
 './dataset/121.xml',
 './dataset/122.xml',
 './dataset/123.xml',
 './dataset/124.xml',
 './dataset/125.xml',
 './dataset/126.xml',
 './dataset/127.xml',
 './dataset/128.xml',
 './dataset/129.xml',
 './dataset/130.xml',
 './dataset/131.xml',
 './dataset/132.xml',
 './dataset/133.xml',
 './dataset/134.xml',
 './dataset/135.xml',
 './dataset/136.xml',
 './dataset/137.xml',
 './dataset/138.xml',
 './dataset/139.xml',
 './dataset/140.xml',
 './dataset/141.xml',
 './dataset/142.xml',
 './dataset/143.xml',
 './dataset/144.xml',
 './dataset/145.xml',
 './dataset/146.xml',
 './dataset/147.xml',
 './dataset/148.xml',
 './dataset/149.xml',
 './dataset/150.xml',
 './dataset/151.xml',
 './dataset/152.xml',
 './dataset/153.xml',
 './dataset/154.xml',
 './dataset/155.xml',
 './dataset/156.xml',
 './dataset/157.xml',
 './dataset/159.xml',
 './dataset/160.xml',
 './dataset/162.xml',
 './dataset/163.xml',
 './dataset/164.xml',
 './dataset/165.xml',
 './dataset/166.xml',
 './dataset/167.xml',
 './dataset/168.xml',
 './dataset/169.xml',
 './dataset/170.xml',
 './dataset/171.xml',
 './dataset/172.xml',
 './dataset/173.xml',
 './dataset/174.xml',
 './dataset/175.xml',
 './dataset/176.xml',
 './dataset/177.xml',
 './dataset/178.xml',
 './dataset/179.xml',
 './dataset/180.xml',
 './dataset/181.xml',
 './dataset/182.xml',
 './dataset/183.xml',
 './dataset/184.xml',
 './dataset/185.xml',
 './dataset/186.xml',
 './dataset/187.xml',
 './dataset/188.xml',
 './dataset/189.xml',
 './dataset/190.xml',
 './dataset/191.xml',
 './dataset/192.xml',
 './dataset/193.xml',
 './dataset/194.xml',
 './dataset/195.xml',
 './dataset/196.xml',
 './dataset/197.xml',
 './dataset/198.xml',
 './dataset/199.xml',
 './dataset/200.xml',
 './dataset/201.xml',
 './dataset/202.xml',
 './dataset/203.xml',
 './dataset/204.xml',
 './dataset/205.xml',
 './dataset/206.xml',
 './dataset/207.xml',
 './dataset/208.xml',
 './dataset/209.xml',
 './dataset/210.xml',
 './dataset/211.xml',
 './dataset/212.xml',
 './dataset/213.xml',
 './dataset/214.xml',
 './dataset/215.xml',
 './dataset/216.xml',
 './dataset/217.xml',
 './dataset/218.xml',
 './dataset/219.xml',
 './dataset/220.xml',
 './dataset/221.xml',
 './dataset/222.xml',
 './dataset/223.xml',
 './dataset/224.xml',
 './dataset/225.xml',
 './dataset/226.xml',
 './dataset/227.xml',
 './dataset/228.xml',
 './dataset/229.xml',
 './dataset/230.xml',
 './dataset/231.xml',
 './dataset/232.xml',
 './dataset/233.xml',
 './dataset/234.xml',
 './dataset/235.xml',
 './dataset/236.xml',
 './dataset/237.xml',
 './dataset/238.xml',
 './dataset/239.xml',
 './dataset/240.xml',
 './dataset/241.xml',
 './dataset/242.xml',
 './dataset/243.xml',
 './dataset/244.xml',
 './dataset/245.xml',
 './dataset/246.xml',
 './dataset/247.xml',
 './dataset/248.xml',
 './dataset/249.xml',
 './dataset/250.xml',
 './dataset/251.xml',
 './dataset/252.xml',
 './dataset/253.xml',
 './dataset/254.xml',
 './dataset/255.xml',
 './dataset/256.xml',
 './dataset/257.xml',
 './dataset/258.xml',
 './dataset/259.xml',
 './dataset/260.xml',
 './dataset/261.xml',
 './dataset/262.xml',
 './dataset/263.xml',
 './dataset/264.xml',
 './dataset/265.xml',
 './dataset/266.xml',
 './dataset/267.xml',
 './dataset/268.xml',
 './dataset/269.xml',
 './dataset/270.xml',
 './dataset/271.xml',
 './dataset/272.xml',
 './dataset/273.xml',
 './dataset/274.xml',
 './dataset/275.xml',
 './dataset/276.xml',
 './dataset/277.xml',
 './dataset/278.xml',
 './dataset/279.xml',
 './dataset/280.xml',
 './dataset/281.xml',
 './dataset/282.xml',
 './dataset/283.xml',
 './dataset/284.xml',
 './dataset/285.xml',
 './dataset/286.xml',
 './dataset/287.xml',
 './dataset/288.xml',
 './dataset/289.xml',
 './dataset/290.xml',
 './dataset/291.xml',
 './dataset/292.xml',
 './dataset/293.xml',
 './dataset/294.xml',
 './dataset/295.xml',
 './dataset/296.xml',
 './dataset/297.xml',
 './dataset/298.xml',
 './dataset/299.xml',
 './dataset/300.xml',
 './dataset/301.xml',
 './dataset/302.xml',
 './dataset/303.xml',
 './dataset/304.xml',
 './dataset/305.xml',
 './dataset/306.xml',
 './dataset/307.xml',
 './dataset/308.xml',
 './dataset/309.xml',
 './dataset/310.xml',
 './dataset/311.xml',
 './dataset/312.xml',
 './dataset/313.xml',
 './dataset/314.xml',
 './dataset/315.xml',
 './dataset/316.xml',
 './dataset/317.xml',
 './dataset/318.xml',
 './dataset/319.xml',
 './dataset/320.xml',
 './dataset/321.xml',
 './dataset/322.xml',
 './dataset/323.xml',
 './dataset/324.xml',
 './dataset/325.xml',
 './dataset/326.xml',
 './dataset/327.xml',
 './dataset/328.xml',
 './dataset/329.xml',
 './dataset/330.xml',
 './dataset/331.xml',
 './dataset/332.xml',
 './dataset/333.xml',
 './dataset/334.xml',
 './dataset/335.xml',
 './dataset/336.xml',
 './dataset/337.xml',
 './dataset/338.xml',
 './dataset/339.xml',
 './dataset/340.xml',
 './dataset/341.xml',
 './dataset/342.xml',
 './dataset/343.xml',
 './dataset/344.xml',
 './dataset/345.xml',
 './dataset/346.xml',
 './dataset/347.xml',
 './dataset/348.xml',
 './dataset/349.xml',
 './dataset/350.xml',
 './dataset/351.xml',
 './dataset/352.xml',
 './dataset/353.xml',
 './dataset/354.xml',
 './dataset/355.xml',
 './dataset/356.xml',
 './dataset/357.xml',
 './dataset/358.xml',
 './dataset/359.xml',
 './dataset/361.xml',
 './dataset/362.xml',
 './dataset/363.xml',
 './dataset/364.xml',
 './dataset/365.xml',
 './dataset/366.xml',
 './dataset/367.xml',
 './dataset/368.xml',
 './dataset/369.xml',
 './dataset/370.xml',
 './dataset/371.xml',
 './dataset/372.xml',
 './dataset/373.xml',
 './dataset/375.xml',
 './dataset/376.xml',
 './dataset/377.xml',
 './dataset/378.xml',
 './dataset/379.xml',
 './dataset/380.xml',
 './dataset/381.xml',
 './dataset/382.xml',
 './dataset/383.xml',
 './dataset/384.xml',
 './dataset/385.xml',
 './dataset/386.xml',
 './dataset/387.xml',
 './dataset/388.xml',
 './dataset/389.xml',
 './dataset/390.xml',
 './dataset/391.xml',
 './dataset/392.xml',
 './dataset/393.xml',
 './dataset/394.xml',
 './dataset/395.xml',
 './dataset/396.xml',
 './dataset/397.xml',
 './dataset/398.xml',
 './dataset/399.xml',
 './dataset/400.xml',
 './dataset/401.xml',
 './dataset/402.xml',
 './dataset/403.xml',
 './dataset/404.xml',
 './dataset/405.xml',
 './dataset/406.xml',
 './dataset/407.xml',
 './dataset/408.xml',
 './dataset/409.xml',
 './dataset/410.xml',
 './dataset/411.xml',
 './dataset/412.xml',
 './dataset/413.xml',
 './dataset/414.xml',
 './dataset/415.xml',
 './dataset/416.xml',
 './dataset/417.xml',
 './dataset/418.xml',
 './dataset/419.xml',
 './dataset/420.xml',
 './dataset/421.xml',
 './dataset/422.xml',
 './dataset/423.xml',
 './dataset/424.xml',
 './dataset/425.xml',
 './dataset/426.xml',
 './dataset/427.xml',
 './dataset/428.xml',
 './dataset/429.xml',
 './dataset/430.xml',
 './dataset/431.xml',
 './dataset/432.xml',
 './dataset/433.xml',
 './dataset/434.xml',
 './dataset/435.xml',
 './dataset/436.xml',
 './dataset/437.xml',
 './dataset/438.xml',
 './dataset/439.xml',
 './dataset/440.xml',
 './dataset/441.xml',
 './dataset/442.xml',
 './dataset/443.xml',
 './dataset/444.xml',
 './dataset/445.xml',
 './dataset/446.xml',
 './dataset/447.xml',
 './dataset/448.xml',
 './dataset/449.xml',
 './dataset/450.xml',
 './dataset/451.xml',
 './dataset/452.xml',
 './dataset/453.xml',
 './dataset/454.xml',
 './dataset/455.xml',
 './dataset/456.xml',
 './dataset/457.xml',
 './dataset/458.xml',
 './dataset/459.xml',
 './dataset/460.xml',
 './dataset/461.xml',
 './dataset/462.xml',
 './dataset/463.xml',
 './dataset/464.xml',
 './dataset/465.xml',
 './dataset/466.xml',
 './dataset/467.xml',
 './dataset/468.xml',
 './dataset/469.xml',
 './dataset/470.xml',
 './dataset/471.xml',
 './dataset/472.xml',
 './dataset/473.xml',
 './dataset/474.xml',
 './dataset/475.xml',
 './dataset/476.xml',
 './dataset/477.xml',
 './dataset/478.xml',
 './dataset/479.xml',
 './dataset/480.xml',
 './dataset/481.xml',
 './dataset/482.xml',
 './dataset/483.xml',
 './dataset/484.xml',
 './dataset/485.xml',
 './dataset/486.xml',
 './dataset/487.xml',
 './dataset/488.xml',
 './dataset/489.xml',
 './dataset/490.xml',
 './dataset/491.xml',
 './dataset/492.xml',
 './dataset/493.xml',
 './dataset/494.xml',
 './dataset/495.xml',
 './dataset/496.xml',
 './dataset/497.xml',
 './dataset/498.xml',
 './dataset/499.xml',
 './dataset/500.xml',
 './dataset/501.xml',
 './dataset/502.xml',
 './dataset/503.xml',
 './dataset/504.xml',
 './dataset/505.xml',
 './dataset/506.xml',
 './dataset/507.xml',
 './dataset/508.xml',
 './dataset/509.xml',
 './dataset/510.xml',
 './dataset/511.xml',
 './dataset/512.xml',
 './dataset/513.xml',
 './dataset/514.xml',
 './dataset/515.xml',
 './dataset/516.xml',
 './dataset/517.xml',
 './dataset/518.xml',
 './dataset/519.xml',
 './dataset/520.xml',
 './dataset/521.xml',
 './dataset/522.xml',
 './dataset/523.xml',
 './dataset/524.xml',
 './dataset/525.xml',
 './dataset/526.xml',
 './dataset/527.xml',
 './dataset/528.xml',
 './dataset/530.xml',
 './dataset/531.xml',
 './dataset/532.xml',
 './dataset/533.xml',
 './dataset/534.xml',
 './dataset/535.xml',
 './dataset/536.xml',
 './dataset/537.xml',
 './dataset/538.xml',
 './dataset/539.xml',
 './dataset/540.xml',
 './dataset/541.xml',
 './dataset/542.xml',
 './dataset/543.xml',
 './dataset/544.xml',
 './dataset/545.xml',
 './dataset/546.xml',
 './dataset/547.xml',
 './dataset/548.xml',
 './dataset/549.xml',
 './dataset/550.xml',
 './dataset/551.xml',
 './dataset/552.xml',
 './dataset/553.xml',
 './dataset/554.xml',
 './dataset/555.xml',
 './dataset/556.xml',
 './dataset/557.xml',
 './dataset/558.xml',
 './dataset/559.xml',
 './dataset/560.xml']

In [39]:
print(len(xmlfiles))

555

### step-2: read xml files
##### * from each xml file we need to extract
##### * filename, size(width, height), object(name, xmin, xmax, ymin, ymax)

In [9]:
def extract_text(filename):
    tree = et.parse(filename)
    root = tree.getroot()

    # extract filename
    image_name = root.find('filename').text
    # width and height of the image
    width = root.find('size').find('width').text
    height = root.find('size').find('height').text
    objs = root.findall('object')
    parser = []
    for obj in objs:
        name = obj.find('name').text
        bndbox = obj.find('bndbox')
        xmin = bndbox.find('xmin').text
        xmax = bndbox.find('xmax').text
        ymin = bndbox.find('ymin').text
        ymax = bndbox.find('ymax').text
        parser.append([image_name, width, height, name,xmin,xmax,ymin,ymax])
        
    return parser

In [10]:
parser_all = list(map(extract_text,xmlfiles))

In [11]:
data = reduce(lambda x, y : x+y,parser_all)

In [12]:
df = pd.DataFrame(data,columns = ['filename','width','height','name','xmin','xmax','ymin','ymax'])

In [13]:
df.head()

  filename width height name xmin  xmax ymin  ymax
0  001.jpg  2048   1536  gun  244  1797   48  1465
1  002.jpg  1459   1094  gun   76  1432  167  1016
2  003.jpg   800    603  gun   17   786   76   593
3  004.jpg  1014    722  gun  101   950  124   656
4  005.jpg  1000    669  gun  165   724   68   493

In [18]:
df.shape

(761, 8)

In [19]:
df['name'].value_counts()

name
person    333
knife     216
gun       212
Name: count, dtype: int64

## Conversion
![conversionIMG.png](conversionIMG.png)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   filename  761 non-null    object
 1   width     761 non-null    object
 2   height    761 non-null    object
 3   name      761 non-null    object
 4   xmin      761 non-null    object
 5   xmax      761 non-null    object
 6   ymin      761 non-null    object
 7   ymax      761 non-null    object
dtypes: object(8)
memory usage: 47.7+ KB

In [21]:
# type conversion
cols = ['width','height','xmin','xmax','ymin','ymax']
df[cols] = df[cols].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   filename  761 non-null    object
 1   width     761 non-null    int64
 2   height    761 non-null    int64
 3   name      761 non-null    object
 4   xmin      761 non-null    int64
 5   xmax      761 non-null    int64
 6   ymin      761 non-null    int64
 7   ymax      761 non-null    int64
dtypes: int64(6), object(2)
memory usage: 47.7+ KB

In [22]:
# center x, center y
df['center_x'] = ((df['xmax']+df['xmin'])/2)/df['width']
df['center_y'] = ((df['ymax']+df['ymin'])/2)/df['height']
# w 
df['w'] = (df['xmax']-df['xmin'])/df['width']
# h 
df['h'] = (df['ymax']-df['ymin'])/df['height']

In [23]:
df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h
0,001.jpg,2048,1536,gun,244,1797,48,1465,0.498291,0.492513,0.758301,0.922526
1,002.jpg,1459,1094,gun,76,1432,167,1016,0.516792,0.540676,0.929404,0.776051
2,003.jpg,800,603,gun,17,786,76,593,0.501875,0.554726,0.961250,0.857380
3,004.jpg,1014,722,gun,101,950,124,656,0.518245,0.540166,0.837278,0.736842
4,005.jpg,1000,669,gun,165,724,68,493,0.444500,0.419283,0.559000,0.635277

### split data into train and test

In [25]:
images = df['filename'].unique()

In [26]:
len(images)

555

In [27]:
# 80% train and 20% test
img_df = pd.DataFrame(images,columns=['filename'])
img_train = tuple(img_df.sample(frac=0.8)['filename']) # shuffle and pick 80% of images

In [28]:
img_test = tuple(img_df.query(f'filename not in {img_train}')['filename']) # take rest 20% images

In [29]:
len(img_train), len(img_test)

(444, 111)

In [30]:
train_df = df.query(f'filename in {img_train}')
test_df = df.query(f'filename in {img_test}')

In [31]:
train_df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h
0,001.jpg,2048,1536,gun,244,1797,48,1465,0.498291,0.492513,0.758301,0.922526
1,002.jpg,1459,1094,gun,76,1432,167,1016,0.516792,0.540676,0.929404,0.776051
3,004.jpg,1014,722,gun,101,950,124,656,0.518245,0.540166,0.837278,0.736842
4,005.jpg,1000,669,gun,165,724,68,493,0.444500,0.419283,0.559000,0.635277
5,005.jpg,1000,669,person,346,986,119,669,0.666000,0.588939,0.640000,0.822123

In [32]:
test_df.head()

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h
2,003.jpg,800,603,gun,17,786,76,593,0.501875,0.554726,0.961250,0.857380
13,012.jpg,2048,1362,gun,6,2025,81,1081,0.495850,0.426579,0.985840,0.734214
16,014.jpg,1024,768,gun,29,1001,86,660,0.502930,0.485677,0.949219,0.747396
23,019.jpg,2047,1280,gun,17,1984,72,1215,0.488764,0.502734,0.960918,0.892969
29,025.jpg,2048,1365,gun,64,1900,132,1360,0.479492,0.546520,0.896484,0.899634

### Assign id number to object names

In [33]:
# label encoding
def label_encoding(x):
    labels = {'person':0, 'knife':1, 'gun':2}
    return labels[x]

In [34]:
train_df['id'] = train_df['name'].apply(label_encoding)
test_df['id'] = test_df['name'].apply(label_encoding)

In [35]:
train_df.head(10)

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h,id
0,001.jpg,2048,1536,gun,244,1797,48,1465,0.498291,0.492513,0.758301,0.922526,2
1,002.jpg,1459,1094,gun,76,1432,167,1016,0.516792,0.540676,0.929404,0.776051,2
3,004.jpg,1014,722,gun,101,950,124,656,0.518245,0.540166,0.837278,0.736842,2
4,005.jpg,1000,669,gun,165,724,68,493,0.444500,0.419283,0.559000,0.635277,2
5,005.jpg,1000,669,person,346,986,119,669,0.666000,0.588939,0.640000,0.822123,0
6,006.jpg,800,600,gun,29,768,156,521,0.498125,0.564167,0.923750,0.608333,2
7,007.jpg,1600,1200,gun,4,1575,161,1063,0.493437,0.510000,0.981875,0.751667,2
8,008.jpg,2048,1536,gun,141,1716,99,1333,0.453369,0.466146,0.769043,0.803385,2
9,009.jpg,800,600,gun,115,745,148,401,0.537500,0.457500,0.787500,0.421667,2
10,009.jpg,800,600,person,14,488,8,600,0.313750,0.506667,0.592500,0.986667,0

In [36]:
test_df.head(10)

,filename,width,height,name,xmin,xmax,ymin,ymax,center_x,center_y,w,h,id
2,003.jpg,800,603,gun,17,786,76,593,0.501875,0.554726,0.961250,0.857380,2
13,012.jpg,2048,1362,gun,6,2025,81,1081,0.495850,0.426579,0.985840,0.734214,2
16,014.jpg,1024,768,gun,29,1001,86,660,0.502930,0.485677,0.949219,0.747396,2
23,019.jpg,2047,1280,gun,17,1984,72,1215,0.488764,0.502734,0.960918,0.892969,2
29,025.jpg,2048,1365,gun,64,1900,132,1360,0.479492,0.546520,0.896484,0.899634,2
30,026.jpg,479,313,gun,21,474,24,270,0.516701,0.469649,0.945720,0.785942,2
54,040.jpg,1024,768,gun,107,925,87,686,0.503906,0.503255,0.798828,0.779948,2
56,042.jpg,1000,750,gun,46,960,66,659,0.503000,0.483333,0.914000,0.790667,2
67,051.jpg,2048,1364,gun,20,1992,127,1073,0.491211,0.439883,0.962891,0.693548,2
71,053.jpg,2048,1373,gun,54,2001,18,1318,0.501709,0.486526,0.950684,0.946832,2

### Save Image and Labels in text

In [40]:
import os
from shutil import move

In [41]:
train_folder = 'dataset/train'
test_folder = 'dataset/test'


os.mkdir(train_folder)
os.mkdir(test_folder)

In [42]:
cols = ['filename','id','center_x','center_y', 'w', 'h']
groupby_obj_train = train_df[cols].groupby('filename')
groupby_obj_test = test_df[cols].groupby('filename')

##### save each image in train/test folder and repective labels in .txt

In [44]:
def save_data(filename, folder_path, group_obj):
    # move image
    src = os.path.join('dataset',filename)
    dst = os.path.join(folder_path,filename)
    move(src,dst) # move image to the destination folder
    
    # save the labels
    text_filename = os.path.join(folder_path,
                                 os.path.splitext(filename)[0]+'.txt')
    group_obj.get_group(filename).set_index('filename').to_csv(text_filename,sep=' ',index=False,header=False)

In [45]:
filename_series = pd.Series(groupby_obj_train.groups.keys())

In [46]:
filename_series.apply(save_data,args=(train_folder,groupby_obj_train))

0      None
1      None
2      None
3      None
4      None
       ...
439    None
440    None
441    None
442    None
443    None
Length: 444, dtype: object

In [47]:
filename_series_test = pd.Series(groupby_obj_test.groups.keys())

In [48]:
filename_series_test.apply(save_data,args=(test_folder,groupby_obj_test))

0      None
1      None
2      None
3      None
4      None
       ...
106    None
107    None
108    None
109    None
110    None
Length: 111, dtype: object